input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["app-logs"]
    codec => json
  }
}

filter {
  ruby {
    code => "event.set('processed_at', Time.now.iso8601)"
  }
  if [level] == "ERROR" {
    mutate { add_field => { "urgency" => "high" } }
  } else {
    mutate { add_field => { "urgency" => "normal" } }
  }
  if [msg] =~ "pirkums" {
    mutate { add_field => { "event_type" => "purchase" } }
  } else if [msg] =~ "mekl" {
    mutate { add_field => { "event_type" => "search" } }
  } else if [msg] =~ "Notikums" {
    mutate { add_field => { "event_type" => "activity" } }
  } else if [level] == "ERROR" {
    mutate { add_field => { "event_type" => "error" } }
  } else {
    mutate { add_field => { "event_type" => "other" } }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
